services:
  - type: web
    name: NatsukashiSong
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: NatsukashiSong
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: NatsukashiSong
    databaseName: NatsukashiSong
    user: NatsukashiSong