services:
  - type: web
    name: natsukasi-song
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mnatsukasi-song-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: natsukasi-song-db
    databaseName: natsukasi-song
    user: natsukasi-song